export const ADD_TODO = 'ADD_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const ADD_ENTER='ADD_ENTER'
export const ADD_EXIT='ADD_EXIT'
export const LogIn='LogIn'